---
apiVersion: v1
kind: Pod
metadata:
   name: rss-oss
   labels:
      app: web
spec:
  containers:
    - name: rss-oss
      image: afcdevacr.azurecr.io/centos-rstudio:v4
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rss-oss-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: rss-oss 
